### ISSUE TITLE
Domain error due to negative GIS volume in GIS.jl

### ISSUE THREAD

**Issue by pwaidelich** [openmodels/META-2021#14]
For outlier Monte Carlo runs under high emissions, `GIS.jl` can produce negative values of the remaining volume of GIS (`VGIS`), which results in domain errors in `vv.VGIS[tt-1] ^ pp.expvol`.

Here's a reproducible example using the example code from the ReadMe:

> include("../src/MimiMETA.jl")
> include("../src/montecarlo.jl")
>
> using Random
> Random.seed!(25081776)
> model = full_model(rcp="RCP8.5", ssp="SSP5")
> draws = getsim(10000, "Fit of Hope and Schaefer (2016)", "Cai et al. central value", "Nordhaus central value",  "Distribution", "Distribution", false, false, false)
> 
> results = runsim(model, draws, true, true, true, "Cai et al. central value", "Distribution")
                                
At about 15% progress, this results in the following error:

> DomainError with -0.32794650642548984:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
in eval at base\boot.jl:368 
in top-level scope at GitHub - Local\META-2021\src\reproduce_gis_error.jl:23
in runsim at GitHub - Local\META-2021\src\montecarlo.jl:224
in var"#runsim#92" at GitHub - Local\META-2021\src\montecarlo.jl:280
in run at Mimi\WsNMq\src\core\instances.jl:341 
in run at Mimi\WsNMq\src\core\instances.jl:341 
in run at Mimi\WsNMq\src\core\instances.jl:366
in run_timestep at Mimi\WsNMq\src\core\instances.jl:326
in run_timestep at Mimi\WsNMq\src\core\instances.jl:317
in run_timestep_Main_GISModel at Mimi\WsNMq\src\core\defcomp.jl:33
in macro expansion at GitHub - Local\META-2021\src\components\GIS.jl:41 
in ^ at base\math.jl:1008
in throw_exp_domainerror at base\math.jl:37

#13 fixes the issue by flooring `VGIS` at zero. Negative VGIS values result in immediate errors, so this should not affect any successful model runs.

**Comment by jrising** [comment]
Thanks @pwaidelich for the fix!
