### ISSUE TITLE
SAF cannot be switched off in Monte Carlo mode

### ISSUE THREAD

**Issue by pwaidelich** [openmodels/META-2021#17]
Currently, `runsim()` in `montecarlo.jl` has no switch to deactivate SAF and always runs the following line of code:

> update_param!(inst, :SAFModel_ECS, draws.TemperatureModel_fair_ECS[ii]) # SAFModel.ECS

Unless I'm overlooking something here, this seems to implicitly assume that the model provided by `full_model()` features the SAF component and hence breaks for runs that feature some tipping points but not SAF, such as the following:

> model = full_model(rcp="RCP4.5", ssp="SSP2", saf = false)
> draws = getsim(50, "Fit of Hope and Schaefer (2016)", "Cai et al. central value", "Nordhaus central value", "Distribution", "none", false, false, false)
> results = runsim(model, draws, true, true, true, "Cai et al. central value", "Distribution")

#16 provides a potential suggestion for adding an SAF switch in Monte Carlo mode

**Comment by pwaidelich** [comment]
I want to turn it on/off in MC mode to isolate the effect of the SAF component on model results (e.g., GDP loss) so I can attribute the overall change with tipping points vis-a-vis the base model without tipping points to the different components. But thanks for the additional context; that's helpful to know!

**Comment by jrising** [comment]
Got it. Okay, you should be good to go! I'll close this.
