### ISSUE TITLE
damagepersist in Consumption.jl not updating with Monte Carlo draws

### ISSUE THREAD

**Issue by pwaidelich** [openmodels/META-2021#18]
When running the model in Monte Carlo mode, I noticed that results are identical if I draw the damage persistence parameter (`damagepersist`) in `Consumption.jl` from its Uniform(0,1) Monte Carlo distribution or leave it at its 0.5 default value.
I've created a reproducible example in my forked repo, in which Monte Carlo results produced by `runsim()` are identical for setting the damage persistence switch in `getsim()` to `true`, for overwriting the Uniform distribution draws with a value of zero, and for dropping the persistence draws from the object returned by `getsim()`:
https://github.com/pwaidelich/META-2021/blob/reprex_MCparam_update/src/reproduce_MCparam_update_error.jl

I think the issue lies in the following if-condition in `runsim()`:
```
if has_parameter(model.md, Symbol(names(draws)[jj]))
       update_param!(inst, Symbol(names(draws)[jj]), draws[ii, jj])
end
``` 

For some reason, this seems to return a `false` for the string "Consumption_damagepersist" (= the persistence column name in the output by `getsim`), whereas it returns a `true` for other parameter names. As a result, the damage persistence parameter is not updated with the Monte Carlo draws.

I am using Mimi v1.5.1 and Julia v1.9.4.

**Comment by jrising** [comment]
I ran into this problem before with the WAIS component not updating. I should have made a general solution at the time. Okay, well I now have a general solution that passes the checks in your code (each of the three `runsim(model, draws_....)` calls produces a different value and the test using an explicit `myupdate_param!` call produces the same result as the `draws_with_persist_overwrite0p0` test).

Check out #19 and let me know if you have any comments before I merge it! Thank you!
