### ISSUE TITLE
getsim() draws GIS variable instead of parameter

### ISSUE THREAD

**Issue by pwaidelich** [openmodels/META-2021#20]
After the fix to #18, the Monte Carlo mode using `getsim()` and `runsim()` produces a new error:

> Cannot find parameter :avoldot in component ComponentPath(Symbol("##ModelDef#899"), :GISModel)
in eval at [base\boot.jl:370](https://github.com/openmodels/META-2021/issues/new#) 
in top-level scope at [deleteme\META-2021\src\repex.jl:48](https://github.com/openmodels/META-2021/issues/new#)
in runsim at [deleteme\META-2021\src\montecarlo.jl:224](https://github.com/openmodels/META-2021/issues/new#)
in var"#runsim#270" at [deleteme\META-2021\src\montecarlo.jl:230](https://github.com/openmodels/META-2021/issues/new#)
in set_param! at [Mimi\OClro\src\core\delegate.jl:54](https://github.com/openmodels/META-2021/issues/new#)
in #set_param!#222 at [Mimi\OClro\src\core\delegate.jl:55](https://github.com/openmodels/META-2021/issues/new#) 
in set_param! at [Mimi\OClro\src\core\defs.jl:515](https://github.com/openmodels/META-2021/issues/new#) 
in var"#set_param!#129" at [Mimi\OClro\src\core\defs.jl:518](https://github.com/openmodels/META-2021/issues/new#)
in kwcall at [Mimi\OClro\src\core\defs.jl:533](https://github.com/openmodels/META-2021/issues/new#)
in var"#set_param!#130" at [Mimi\OClro\src\core\defs.jl:537](https://github.com/openmodels/META-2021/issues/new#)
in error at [base\error.jl:35](https://github.com/openmodels/META-2021/issues/new#)

Here's a reproducible example using the example code for `runsim()` from the ReadMe but using `"Distribution"` instead of `"Nordhaus central value"` for the `gis_calib` function argument in `getsim():`

```
include("../src/MimiMETA.jl")
include("../src/montecarlo.jl")
model = full_model(rcp="RCP4.5", ssp="SSP2")
draws = getsim(100,
               "Kessler probabilistic", # PCF
               "Distribution", # AMAZ
               "Distribution", # GIS
               "Distribution", # WAIS
               "Distribution", # SAF
               false, # persit
               false, # emuc
               false) # prtp
results = runsim(model, draws,
                 true, # ism_used
                 true, # omh_used
                 true, # amoc_used
                 true, # saf_used
                 "Cai et al. central value", # AMAZ
                 "Distribution") # WAIS
```

The issue is that `getsim()` produces a draw with column name `GISModel_avoldot`, which is a variable in `GIS.jl`, not a parameter. Probably the error did not come up before because the parameter was not correctly updated with Monte Carlo draws (see #18). The name of the actual parameter is `avoldot0`. Since `vv.avoldot = pp.avoldot0 * pp.meltmult` (`GIS.jl`, l. 28) and `pp.meltmult` only takes values of one (see `data/GISparams.csv`), a simple fix in `getsim()` seems changing the name from `GISModel_avoldot` to `GISModel_avoldot0`.

But I'm not 100% sure this is compatible with non-Nordhaus specifications of the GIS component (`Robinson` and `Non-linear equilibrium function`)

**Comment by jrising** [comment]
Thank you for this fix! Yes, `avoldot0` is definitely the right parameter to update, since we have that `meltmult` logic. PR #21 opened.

@sidietz79 Was the Excel version ever set up to handle the non-Nordhaus calibration? I can't tell how these were meant to be used. Do these just replace isolated values in the Nordhaus calibration?

**Comment by sidietz79** [comment]
@jrising @pwaidelich we did not get around to actually running the Non-Nordhaus calibration when producing the PNAS paper. Nordhaus' own analysis indicates this choice of calibration is not important, but I think the reason we didn't get to it was basically just time/size constraints related to the paper. It is easy to do in principle. You need to set tmaxa=1.8 but also avoldot0=-0.0000088.
